name: Test

on: [push, pull_request]

jobs:
  test:
   runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up Python 
      uses: actions/setup-python@v5.3.0
      with:
        python-version: '3.13'
    - name: Install test dependencies
      run: python -m pip install --upgrade nox
    - name: Test
      run: python -m nox -s tests
    - name: Lint
      run: python -m nox -s lint
    - name: output
      run : python --version
    - 
